name: hotly
description: A Flutter package for testing via an isolate improving performance.
version: 0.1.0
homepage: https://github.com/P-Rosa3008/hotly

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  test_api: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.hotly
        pluginClass: HotlyPlugin
      ios:
        pluginClass: HotlyPlugin
