name: hotly
description: A Flutter package for testing via an isolate improving performance.
version: 0.1.0
homepage: https://github.com/P-Rosa3008/hotly
publish_to: 'https://pub.dev'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.hotly
        pluginClass: HotlyPlugin
      ios:
        pluginClass: HotlyPlugin
